# Generated by Django 3.2.15 on 2026-06-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_promptsnippet'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promptsnippet',
            name='prompt_snip_created_26ad96_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptsnippet',
            name='prompt_snip_created_230d65_idx',
        ),
        migrations.AddIndex(
            model_name='promptsnippet',
            index=models.Index(fields=['created_by', 'node_type', 'is_active'], name='prompt_snip_created_788eef_idx'),
        ),
        migrations.AddIndex(
            model_name='promptsnippet',
            index=models.Index(fields=['created_by', 'category', 'is_active'], name='prompt_snip_created_57ab36_idx'),
        ),
    ]
